/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/action-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Action Types
         * @description Derived from the handler registry: a new handler shows up here for free.
         */
        get: operations["list_action_types_action_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_actions_get"];
        put?: never;
        /** Create Action */
        post: operations["create_action_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Action */
        get: operations["get_action_actions__action_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Action */
        post: operations["complete_action_actions__action_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Action Document */
        post: operations["upload_action_document_actions__action_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionCreate
         * @description The union documents the accepted shapes; the service re-validates `payload`
         *     against the `creation_model` of the declared `type`, which is authoritative.
         */
        ActionCreate: {
            type: components["schemas"]["ActionType"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Requester */
            requester: string;
            /** Payload */
            payload: components["schemas"]["DeploymentReviewCreate"] | components["schemas"]["DocumentationUploadCreate"] | components["schemas"]["ExpenseApprovalCreate"] | components["schemas"]["OnboardingCreate"];
        };
        /**
         * ActionRead
         * @description Wire representation of an Action. Per-type bodies live with their handler.
         */
        ActionRead: {
            /** Id */
            id: string;
            type: components["schemas"]["ActionType"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Requester */
            requester: string;
            status: components["schemas"]["ActionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "pending" | "completed";
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "expense_approval" | "deployment_review" | "documentation_upload" | "onboarding";
        /**
         * ActionTypeDescriptor
         * @description What the UI needs to offer a type and render its creation form.
         */
        ActionTypeDescriptor: {
            type: components["schemas"]["ActionType"];
            /** Label */
            label: string;
            /**
             * Completion
             * @enum {string}
             */
            completion: "json" | "file";
            /** Schema Name */
            schema_name: string;
            /** Payload Schema */
            payload_schema: {
                [key: string]: unknown;
            };
        };
        /** Body_upload_action_document_actions__action_id__upload_post */
        Body_upload_action_document_actions__action_id__upload_post: {
            /** File */
            file: string;
        };
        /** DeploymentReviewCreate */
        DeploymentReviewCreate: {
            /** Servicio */
            service: string;
            /** Versión */
            version: string;
            /**
             * Entorno
             * @description Ej. staging, production.
             */
            environment: string;
        };
        /** DocumentationUploadCreate */
        DocumentationUploadCreate: {
            /** Nombre del documento */
            document_name: string;
        };
        /** ExpenseApprovalCreate */
        ExpenseApprovalCreate: {
            /**
             * Monto
             * @description Importe del gasto, mayor a cero.
             */
            amount: number;
            /**
             * Moneda
             * @description Código ISO de 3 letras, ej. ARS.
             */
            currency: string;
            /**
             * Comprobante (URL)
             * Format: uri
             */
            receipt_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OnboardingCreate */
        OnboardingCreate: {
            /** Nombre del empleado */
            employee_name: string;
            /**
             * Checklist
             * @description Pasos a completar durante el onboarding.
             */
            checklist: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_action_types_action_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionTypeDescriptor"][];
                };
            };
        };
    };
    list_actions_actions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ActionStatus"] | null;
                type?: components["schemas"]["ActionType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_action_actions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_action_actions__action_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_action_actions__action_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } & ({
                    /** Approved */
                    approved: boolean;
                    /** Notes */
                    notes: string;
                } | {
                    /** Approved */
                    approved: boolean;
                    /** Comment */
                    comment: string;
                } | {
                    /** Completed Steps */
                    completed_steps: string[];
                });
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_action_document_actions__action_id__upload_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_action_document_actions__action_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
